app/models.py
from app import db
from werkzeug.security import generate_password_hash, check_password_hash

class User(db.Model):
    __tablename__ = "users"

    id                 = db.Column(db.Integer(), primary_key=True)
    username           = db.Column(db.String(64), unique=True, nullable=False)
    email              = db.Column(db.String(64), unique=True, index=True, nullable=False)
    description        = db.Column(db.Text(), nullable=False)
    location           = db.Column(db.String(255), nullable=False)
    password_hash      = db.Column(db.String(255), nullable=False)
    
    def __init__(self, username="", email="", password="", location="", description=""):
        self.username         = username
        self.email            = email
        self.password_hash    = generate_password_hash(password)
        self.location         = location
        self.description      = description

    def __repr__(self):
        return '<User %r>' % self.username

    @property
    def password(self):
        raise AttributeError("Password should not be read like this")

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

app/__init__.py
import os
from flask import Flask, render_template
from flask_sqlalchemy import SQLAlchemy

basedir = os.path.abspath(os.path.dirname(__file__))
db = SQLAlchemy()

def create_app():
    app = Flask(__name__)
    app.config.from_mapping(
        SECRET_KEY=os.getenv("FLASK_SECRET_KEY") or 'prc9FWjeLYh_KsPGm0vJcg',
        SQLALCHEMY_DATABASE_URI='sqlite:///'+ os.path.join(basedir, 'globomantics.sqlite'),
        SQLALCHEMY_TRACK_MODIFICATIONS=False,
        DEBUG=True
    )

    db.init_app(app)

    from app.auth.views import auth
    from app.main.views import main
    app.register_blueprint(auth)
    app.register_blueprint(main)

    from app.main.errors import page_not_found
    app.register_error_handler(404, page_not_found)

    return app

app/main/views.py
from flask import Blueprint, render_template
from app.models import User

main = Blueprint('main', __name__, template_folder='templates')

@main.route('/')
def home():
	users = User.query.all()
	return render_template('home.html', users=users)

app/templates/_error_messages.html
{% macro error_messages(errors) %}
{% if errors %}
<div class="alert alert-danger">
  {% for field in errors %}
    <b>{{ field | capitalize }} field has following errors:</b><br>
    {% for error in errors[field] %}
    {{ error }}<br>
    {% endfor %}
  {% endfor %}
</div>
{% endif %}
{% endmacro %}

{% macro field_error_messages(field) %}
{% if field.errors %}
<br>
<ul>
{% for error in field.errors %}
<li style="color:red">
  {{ error }}
</li>
{% endfor %}
</ul>
{% endif %}
{% endmacro %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>{% block title %}{% endblock %}Globomantics</title>

  <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
    <div class="container">
      <a href="{{ url_for('main.home') }}" class="navbar-brand">
        <img src="{{ url_for('static', filename='images/logo.png') }}" height="40px">
      </a>
      <button class="navbar-toggler" type="button"
              data-toggle="collapse" data-target="#navbarResponsive"
              aria-controls="navbarResponsive" aria-expanded="false"
              aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item {{ 'active' if active_page == 'home' }}">
            <a href="{{ url_for('main.home') }}" class="nav-link">Home</a>
          </li>
          <li class="nav-item {{ 'active' if active_page == 'register' }}">
            <a href="{{ url_for('auth.register') }}" class="nav-link">Register</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <div class="container">
  {% with messages = get_flashed_messages(with_categories=True) %}
    {% if messages %}
      {% for type, content in messages %}
        <div class="alert alert-{{ type }} alert-dismissible my-4" role="alert">
          <button type="button" class="close"
                  data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          {{ content }}
        </div>
      {% endfor %}
    {% endif %}
  {% endwith %}
  {% block content %}{% endblock %}
  </div>

  <script src="{{ url_for('static', filename='js/jquery-3.4.1.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
  {% block javascript %}{% endblock %}
</body>

</html>